"""Initial Migration

Revision ID: 288705f4d2a5
Revises: 
Create Date: 2024-03-16 00:20:09.391157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288705f4d2a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_pizza_place', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_pizza_place')

    # ### end Alembic commands ###
