"""password field for users

Revision ID: 910cea5fa1e2
Revises: 288705f4d2a5
Create Date: 2024-03-16 14:04:36.537197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910cea5fa1e2'
down_revision = '288705f4d2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
